trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'mapper-app'

steps:
- task: Docker@2
  displayName: Build and Push to ACR
  inputs:
    command: buildAndPush
    repository: $(IMAGE_NAME)
    dockerfile: Dockerfile
    containerRegistry: sc-acr
    tags: latest

- task: AzureContainerApps@1
  displayName: Deploy to Azure Container Apps
  inputs:
    azureSubscription: sc-azure-rm
    resourceGroup: rg-mapper
    containerAppName: mapper-app
    imageToDeploy: $(IMAGE_NAME):latest
    containerRegistry: acrmapper15214.azurecr.io
    targetPort: 8501
