name: Build & Deploy to Azure Container Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  AZ_RG: rg-mapper
  AZ_CONTAINER_APP: mapper-app
  AZ_CONTAINER_ENV: env-mapper
  ACR_NAME: acrmapper15214
  IMAGE_NAME: mapper-app

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # <<< IMPORTANT: Service principal JSON login >>>
      - name: Azure login (service principal JSON)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Show account (sanity check)
        run: az account show

      - name: Get ACR login server
        run: echo "ACR_LOGIN_SERVER=$(az acr show -n $ACR_NAME --query loginServer -o tsv)" >> $GITHUB_ENV

      - name: ACR login (via Azure token)
        run: az acr login -n $ACR_NAME

      - name: Build & Push image
        run: |
          IMAGE_TAG=${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${GITHUB_SHA}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Deploy to Container Apps
        uses: Azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.AZ_RG }}
          containerAppName: ${{ env.AZ_CONTAINER_APP }}
          imageToDeploy: ${{ env.IMAGE_TAG }}
          environmentToUse: ${{ env.AZ_CONTAINER_ENV }}
          ingress: external
          targetPort: 8501
