name: Build & Deploy to Azure Container Apps

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AZ_RG: rg-mapper
  AZ_CONTAINER_APP: mapper-app
  AZ_CONTAINER_ENV: env-mapper
  ACR_LOGIN_SERVER: acrmapper15214.azurecr.io
  IMAGE_NAME: mapper-app

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker login to ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push image
        run: |
          IMAGE_TAG=${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Deploy to Azure Container Apps
        uses: Azure/container-apps-deploy-action@v2
        with:
          resourceGroup: ${{ env.AZ_RG }}
          containerAppName: ${{ env.AZ_CONTAINER_APP }}
          imageToDeploy: ${{ env.IMAGE_TAG }}
          environmentToUse: ${{ env.AZ_CONTAINER_ENV }}
          ingress: external
          targetPort: 8501
